[package]
name = "bitcraft-macro"
version = "0.1.0"
authors = ["Alexandre Gauthier<alexandre@clockworklabs.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "*"